### ISSUE TITLE
Error: Could not append entry, key ... is not allowed to write to the log

### ISSUE THREAD

**Issue by aturX** [3box/3box-js#897] opened 2020-08-21 04:43 UTC
**Describe the bug**
"Error: Could not append entry, key "did:3:bafyreig4trqtifolb3mw7b6elt5butfb23gj2n6dugtjm2gwt63symqvb4" is not allowed to write to the log"

I can not write new data , can not change data, but I can read data from 3box
 

I can not write data to 3box , when I  open a new.
This is my code 
```
            this.box = await Box.openBox(this.address, window.ethereum)
            this.box.syncDone

            console.log(this.box)
 
            const spaces = ['ant-cave']
            const address = this.address
            await this.box.auth(spaces, { address })
            await this.box.public.set('name', 'oed')
            console.log(this.box)
```

**Comment by oed** [comment] 2020-08-26 09:22
Duplicate of https://github.com/3box/3box-js/issues/872

**Closed by oed** 2020-08-26 09:22 UTC
