### ISSUE TITLE
Error: Could not validate signature "1232...." for entry "zdpu...HcuC" when in openBox

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#524] opened 2019-07-16 19:43 UTC
I noticed this myself during development,  but recently got a message from discord user AneoPsy for the same issue so escalating it here.

From AneoPsy:
```
Error: Could not validate signature "304402204...dac0ad55a472" for entry "zdpu...HcuC" and key "0489cd0a734f697f...6cf8349783fe9154fb33ab358c8a6"

I have this error on all new account create on my dApp, Old account still woking but new account throw this error on the openBox() function
```

From @oznekenzo:
the error with dapper `Could not validate signature "304...308" for entry "zdpuAtFcidhn1XZ"` is happening in the log.js file in the ipfs-log node package required in the 3box-js lib

**Comment by oed** [comment] 2019-07-16 20:39
Thanks for creating the ticket! Have you been able to reproduce this reliably? If so with what steps?

**Comment by zachferland** [comment] 2019-07-18 19:48
No matter what i do this can no be replicated in the library/example. But it is easy to replicate in the dapp (cc @oznekenzo ) 

1) new account
2) log in 
3) sign open message
3) sign link message
4) update status 
5) log in again, and error throws

No more details yet

**Comment by oed** [comment] 2019-07-19 09:38
I'm not seeing the issue now by doing the steps above. Was this fixed? Looks like it's only fixed for new accounts and not for accounts where the issue is already present?

**Comment by zachferland** [comment] 2019-07-19 16:37
No longer exist for new accounts being created, but accounts created during the three days the issue was deployed will still see issue until follow in linked issue.  Closing now, replaced by follow up issue.

**Closed by zachferland** 2019-07-19 16:37 UTC
Labels: bug, needs replication
